### ISSUE TITLE
[Docs]: Review README.md grammar

### ISSUE THREAD

**Issue by kpicaza** [drinksandco/symfony-console-ui#19]
We need to review our README grammar. It is fast written at the moment, but now we need more comprehensible docs

**Comment by VividhPandey003** [comment]
Hey, I am a beginner to Open Source and would love to contribute to this issue. Could you please assign this issue to me under Hacktoberfest.⭐️

**Comment by VividhPandey003** [comment]
Thanks a lot for assigning this issue to me @kpicaza

**Comment by kpicaza** [comment]
You are welcome ;-D @VividhPandey003

**Comment by VividhPandey003** [comment]
@kpicaza I have made the changes which I felt were necessary. I would request you to review my changes once after I submit my Pull Request. 
I will be submitting my Pull Request as soon as Hacktoberfest starts so that it counts up in my Hacktoberfest Journey.

**Comment by VividhPandey003** [comment]
Hey @kpicaza I've made a Pull Request. Could you please approve the workflow , review the pull request and tell me if I need to make any changes.😊
<img width="946" alt="image" src="https://user-images.githubusercontent.com/91251535/193350013-0647079d-59ae-4a1a-9e47-ee2d139a43dc.png">
